# Do not build tags and feature branches
skip_tags: true
skip_branch_with_pr: true

# Project configuration
image: Visual Studio 2019
platform: Any CPU
configuration: Release

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to

before_build:
  # Check SDKs
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\\""
  # Generates a temporary SNK. Not for real signing
  - cmd: "\"C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools\\sn.exe\" -k winsw_key.snk"

dotnet_csproj:
  patch: true
  file: "**\\*.csproj"
  version: $(appveyor_build_version)

build:
  parallel: true 
  project:  src\winsw.sln 

after_build:
  - ps: nuget pack WinSW.nuspec -Version $env:APPVEYOR_BUILD_VERSION

test_script:
# Runner for NUnit2
- ps: nunit-console 'src/Test/winswTests/bin/Release/net40/winswTests.dll' 'src/Test/winswTests/bin/Release/net40/SharedDirectoryMapper.dll' 'src/Test/winswTests/bin/Release/net40/RunawayProcessKiller.dll'

artifacts:
  - path: 'src/Core/ServiceWrapper/bin/Release/net20/WinSW.exe'
    name: WinSW.NET2.exe
  - path: 'src/Core/ServiceWrapper/bin/Release/net40/WinSW.exe'
    name: WinSW.NET4.exe
  - path: 'WinSW.$(appveyor_build_version).nupkg'
    name: WinSW.nupkg
  - path: 'examples/sample-allOptions.xml'
    name: 'sample-allOptions.xml'
  - path: 'examples/sample-minimal.xml'
    name: 'sample-minimal.xml'
